name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: Creates output
        run: sh ./build.sh

      - name: Clone destination repository
        run: |
          git clone https://x-access-token:${{ secrets.AUTO_ACTIONS }}@github.com/evaain706/WINE.git dest-repo

      - name: Sync output to destination branch
        run: |
          cd dest-repo
          git checkout ${{ github.ref_name }}
          rsync -av --delete ../output/ .
          git config user.name "github-actions"
          git config user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -m "Auto-deploy: ${{ github.event.head_commit.message }}" || echo "No changes"
          git push origin ${{ github.ref_name }}

      - name: Confirm deployment branch
        run: echo "Synced to branch: ${{ github.ref_name }}"